sudo: required

language: go

go:
  - 1.4
  - 1.5
  - 1.6

python:
  - 3.4

node_js:
  - 6.3

before_install:
  - go get github.com/raindevteam/gorml
#  - sudo apt-get install python3-pip
#  - sudo pip3 install pyrml
  - cd tests/modules/jsmod && npm install && cd -

install:
  - go get -d ./...

script: 
  - go test -race -v ./rbot ./tmpl ./parser
