language: go

go:
  - 1.6
  - 1.7
  - 1.8

install:
  - go version
  - go get -d ./...
  - chmod +x ./tools/build.sh
  - chmod +x ./tools/test.sh
  # Generate handler code.
  - ./tools/build.sh

script: 
  - ./tools/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
