sudo: required
dist: trusty

language: go

virtualenv:
  system_site_packages: true

go:
  - 1.4
  - 1.5
  - 1.6

node_js:
  - 6.3

before_install:
  - go get github.com/raindevteam/gorml
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip
  - export PYTHONPATH=/usr/lib/python3/dist-packages:/usr/local/lib/python3.5/dist-packages
  - sudo pip3 install pyrml
  - cd tests/modules/jsmod && npm install && cd -

install:
  - pip3 --version
  - python3 --version
  - node -v
  - go version
  - go get -d ./...

script: 
  - go test -race -v ./rbot ./tmpl ./parser
