sudo: required
dist: trusty

language: go

go:
  - 1.4
  - 1.5
  - 1.6

addons:
  apt:
    sources:
    - deadsnakes

before_install:
  # Go RML
  - go get github.com/raindevteam/gorml

  # Python RML
  - sudo apt-get install -y python3.5
  - sudo apt-get install -y python3-pip
  - sudo pip3 install pyrml

  # JavaScript RML
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && sudo apt-get install -y nodejs
  - cd tests/modules/jsmod && npm install && cd $HOME/gopath/src/github.com/raindevteam/rain

install:
  - go install
  - rain depends

script: 
  - go test -race -v ./rbot ./tmpl ./parser
