language: go

go:
  - 1.6
  - 1.7
  - 1.8

install:
  - go version
  - go get -d ./...

script: 
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./rbot ./handler ./hail

after_success:
  - bash <(curl -s https://codecov.io/bash)
