sudo: required
dist: trusty

language: go

go:
  - 1.4
  - 1.5
  - 1.6

addons:
  apt:
    sources:
    - deadsnakes
    - key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    - sourceline: 'deb https://deb.nodesource.com/node_6.x trusty main'
    packages:
    - python3.5
    - python3-pip
    - nodejs

before_install:
  # Go RML
  - go get github.com/raindevteam/gorml
  # Python RML
  - sudo pip3 install pyrml
  # JavaScript RML
  - npm install --prefix ./tests/modules/jsmod/node_modules

install:
  - go get -d ./...

script: 
  - go test -race -v ./rbot ./tmpl ./parser
