sudo: required
dist: trusty

language: go

go:
  - 1.4
  - 1.5
  - 1.6

python:
  - 3.4

node_js:
  - 6.3

before_install:
  - go get github.com/raindevteam/gorml
  - sudo apt-get install -y python3-pip
  - sudo pip3 install -y pyrml
  - cd tests/modules/jsmod && npm install && cd -

install:
  - python3 --version
  - node -v
  - go version
  - go get -d ./...

script: 
  - go test -race -v ./rbot ./tmpl ./parser
